#ifndef _AFP_IPC_H_
#define _AFP_IPC_H_

#include <stdint.h>

#ifndef MAX_CLIENT_RESPONSE
#define MAX_CLIENT_RESPONSE 16384
#endif

/* Unix socket shared by afpsld and libafpsl. */
#define SERVER_SL_SOCKET_PATH "/tmp/afp_sl"

/* Structured logging trailer appended to stateless daemon responses. */
#define AFP_SERVER_LOG_MAGIC UINT32_C(0x4146504c)
#define AFP_SERVER_LOG_BUFFER_SIZE 4096

struct afp_server_log_record {
    int32_t level;
    uint32_t message_len;
};

struct afp_server_log_footer {
    uint32_t magic;
    uint32_t log_len;
};

/* IPC command codes shared between daemon, FUSE, and client components */

#define AFP_SERVER_COMMAND_MOUNT 1
#define AFP_SERVER_COMMAND_ATTACH 2
#define AFP_SERVER_COMMAND_DETACH 3
#define AFP_SERVER_COMMAND_STATUS 4
#define AFP_SERVER_COMMAND_UNMOUNT 6
#define AFP_SERVER_COMMAND_SUSPEND 8
#define AFP_SERVER_COMMAND_RESUME 9
#define AFP_SERVER_COMMAND_PING 11
#define AFP_SERVER_COMMAND_EXIT 12
#define AFP_SERVER_COMMAND_CONNECT 14
#define AFP_SERVER_COMMAND_GETVOLID 16
#define AFP_SERVER_COMMAND_READDIR 19
#define AFP_SERVER_COMMAND_GETVOLS 20
#define AFP_SERVER_COMMAND_STAT 21
#define AFP_SERVER_COMMAND_OPEN 22
#define AFP_SERVER_COMMAND_READ 23
#define AFP_SERVER_COMMAND_CLOSE 24
#define AFP_SERVER_COMMAND_SERVERINFO 25
#define AFP_SERVER_COMMAND_GET_MOUNTPOINT 26
#define AFP_SERVER_COMMAND_WRITE 27
#define AFP_SERVER_COMMAND_CREAT 28
#define AFP_SERVER_COMMAND_CHMOD 29
#define AFP_SERVER_COMMAND_RENAME 30
#define AFP_SERVER_COMMAND_UNLINK 31
#define AFP_SERVER_COMMAND_TRUNCATE 32
#define AFP_SERVER_COMMAND_MKDIR 33
#define AFP_SERVER_COMMAND_RMDIR 34
#define AFP_SERVER_COMMAND_STATFS 35
#define AFP_SERVER_COMMAND_UTIME 36
#define AFP_SERVER_COMMAND_DISCONNECT 37
#define AFP_SERVER_COMMAND_CHANGEPW 38
#define AFP_SERVER_COMMAND_GETXATTR 39
#define AFP_SERVER_COMMAND_SETXATTR 40
#define AFP_SERVER_COMMAND_LISTXATTR 41
#define AFP_SERVER_COMMAND_REMOVEXATTR 42
#define AFP_SERVER_COMMAND_GETFINDERINFO 43
#define AFP_SERVER_COMMAND_SETFINDERINFO 44
#define AFP_SERVER_COMMAND_REMOVEFINDERINFO 45
#define AFP_SERVER_COMMAND_GETRESOURCEFORK 46
#define AFP_SERVER_COMMAND_SETRESOURCEFORK 47
#define AFP_SERVER_COMMAND_REMOVERESOURCEFORK 48
#define AFP_SERVER_COMMAND_TRUNCATERESOURCEFORK 49

/* IPC result codes */

#define AFP_SERVER_RESULT_OKAY 0
#define AFP_SERVER_RESULT_ERROR 1
#define AFP_SERVER_RESULT_TRYING 2
#define AFP_SERVER_RESULT_WARNING 3
#define AFP_SERVER_RESULT_ENOENT 4
#define AFP_SERVER_RESULT_NOTCONNECTED 5
#define AFP_SERVER_RESULT_NOTATTACHED 6
#define AFP_SERVER_RESULT_ALREADY_CONNECTED 7
#define AFP_SERVER_RESULT_ALREADY_ATTACHED 8
#define AFP_SERVER_RESULT_NOAUTHENT 9
#define AFP_SERVER_RESULT_ERROR_UNKNOWN 10
#define AFP_SERVER_RESULT_NOVOLUME 14
#define AFP_SERVER_RESULT_ALREADY_MOUNTED 15
#define AFP_SERVER_RESULT_VOLPASS_NEEDED 16
#define AFP_SERVER_RESULT_MOUNTPOINT_NOEXIST 17
#define AFP_SERVER_RESULT_NOSERVER 18
#define AFP_SERVER_RESULT_MOUNTPOINT_PERM 19
#define AFP_SERVER_RESULT_TIMEDOUT 20
#define AFP_SERVER_RESULT_DAEMON_ERROR 21
#define AFP_SERVER_RESULT_NOTSUPPORTED 22
#define AFP_SERVER_RESULT_ACCESS 23
#define AFP_SERVER_RESULT_EXIST 24
#define AFP_SERVER_RESULT_ENOTEMPTY 25

#endif
