name: Build

on:
  push:
    branches: ["main"]
    paths-ignore:
      - 'AUTHORS'
      - 'BUGS'
      - 'COPYING'
      - 'INSTALL.md'
      - 'NEWS'
      - 'README.md'
      - 'TODO'

  pull_request:
    branches: ["main"]
    types:
      - opened
      - synchronize
      - reopened
    paths-ignore:
      - 'AUTHORS'
      - 'BUGS'
      - 'COPYING'
      - 'INSTALL.md'
      - 'NEWS'
      - 'README.md'
      - 'TODO'

env:
  SMARTOS_BOOTSTRAP_URL: https://pkgsrc.smartos.org/packages/SmartOS/bootstrap/bootstrap-2025Q4-x86_64.tar.gz
  SMARTOS_BOOTSTRAP_SHA256: 4842f72b610d44cf98560253b6bf16ff4056016e5fe2c6932bc195156ac75772

jobs:
  build-alpine-fuse2:
    name: Alpine Linux (with FUSE v2)
    runs-on: ubuntu-latest
    container:
      image: alpine:3.22.1
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Install dependencies
        run: |
          apk add --no-cache \
            avahi-dev \
            build-base \
            fuse-dev \
            libedit-dev \
            libgcrypt-dev \
            meson \
            ninja
      - name: Setup
        run: meson setup build --prefix=/usr
      - name: Compile
        run: meson compile -C build
      - name: Test
        run: meson test -C build
      - name: Install
        run: meson install -C build
      - name: Run
        run: afpcmd -h
      - name: Upload meson logs
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: meson-logs-${{ github.job }}
          path: build/meson-logs

  build-alpine-fuse3:
    name: Alpine Linux (with FUSE v3)
    runs-on: ubuntu-latest
    container:
      image: alpine:3.22.1
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Install dependencies
        run: |
          apk add --no-cache \
            avahi-dev \
            build-base \
            fuse3-dev \
            libedit-dev \
            libgcrypt-dev \
            meson \
            ninja
      - name: Setup
        run: meson setup build --prefix=/usr
      - name: Compile
        run: meson compile -C build
      - name: Test
        run: meson test -C build
      - name: Install
        run: meson install -C build
      - name: Run
        run: afpcmd -h
      - name: Upload meson logs
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: meson-logs-${{ github.job }}
          path: build/meson-logs

  build-fedora-fuse2:
    name: Fedora Linux (with FUSE v2)
    runs-on: ubuntu-latest
    container:
      image: fedora:42
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Install dependencies
        run: |
          dnf --setopt=install_weak_deps=False --assumeyes install \
            avahi-devel \
            fuse-devel \
            gcc \
            libgcrypt-devel \
            meson \
            ninja-build \
            readline-devel
      - name: Setup
        run: meson setup build --prefix=/usr
      - name: Compile
        run: meson compile -C build
      - name: Test
        run: meson test -C build
      - name: Install
        run: sudo meson install -C build
      - name: Run
        run: afpcmd -h
      - name: Upload meson logs
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: meson-logs-${{ github.job }}
          path: build/meson-logs

  build-fedora-fuse3:
    name: Fedora Linux (with FUSE v3)
    runs-on: ubuntu-latest
    container:
      image: fedora:42
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Install dependencies
        run: |
          dnf --setopt=install_weak_deps=False --assumeyes install \
            avahi-devel \
            fuse3-devel \
            gcc \
            libgcrypt-devel \
            meson \
            ninja-build \
            readline-devel
      - name: Setup
        run: meson setup build --prefix=/usr
      - name: Compile
        run: meson compile -C build
      - name: Test
        run: meson test -C build
      - name: Install
        run: sudo meson install -C build
      - name: Run
        run: afpcmd -h
      - name: Upload meson logs
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: meson-logs-${{ github.job }}
          path: build/meson-logs

  build-ubuntu-fuse2:
    name: Ubuntu 22.04 (with FUSE v2)
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --assume-yes --no-install-recommends \
            gcc \
            libavahi-core-dev \
            libbsd-dev \
            libgcrypt-dev \
            libfuse-dev \
            libreadline-dev \
            ninja-build \
            pkg-config \
            python3-pip
          sudo python3 -m pip install --upgrade meson
      - name: Setup
        run: meson setup build --prefix=/usr
      - name: Compile
        run: meson compile -C build
      - name: Test
        run: meson test -C build
      - name: Install
        run: sudo meson install -C build
      - name: Run
        run: afpcmd -h
      - name: Upload meson logs
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: meson-logs-${{ github.job }}
          path: build/meson-logs

  build-ubuntu-fuse3:
    name: Ubuntu 24.04 (with FUSE v3)
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --assume-yes --no-install-recommends \
            gcc \
            libavahi-core-dev \
            libgcrypt-dev \
            libfuse3-dev \
            libreadline-dev \
            meson \
            ninja-build \
            pkg-config
      - name: Setup
        run: meson setup build --prefix=/usr
      - name: Compile
        run: meson compile -C build
      - name: Test
        run: meson test -C build
      - name: Install
        run: sudo meson install -C build
      - name: Run
        run: afpcmd -h
      - name: Upload meson logs
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: meson-logs-${{ github.job }}
          path: build/meson-logs

  build-macos-fuse2:
    name: macOS (with FUSE v2)
    runs-on: macos-latest
    env:
      HOMEBREW_NO_INSTALL_CLEANUP: 1
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Install dependencies
        run: |
          brew update
          brew install \
            macfuse \
            meson
      - name: Setup
        run: meson setup build -Dforce-fuse-v2=true
      - name: Compile
        run: meson compile -C build
      - name: Test
        run: meson test -C build
      - name: Install
        run: sudo meson install -C build
      - name: Run
        run: afpcmd -h
      - name: Upload meson logs
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: meson-logs-${{ github.job }}
          path: build/meson-logs

  build-macos-fuse3:
    name: macOS (with FUSE v3)
    runs-on: macos-latest
    env:
      HOMEBREW_NO_INSTALL_CLEANUP: 1
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Install dependencies
        run: |
          brew update
          brew install \
            macfuse \
            meson
      - name: Setup
        run: meson setup build
      - name: Compile
        run: meson compile -C build
      - name: Test
        run: meson test -C build
      - name: Install
        run: sudo meson install -C build
      - name: Run
        run: afpcmd -h
      - name: Upload meson logs
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: meson-logs-${{ github.job }}
          path: build/meson-logs

  build-freebsd-fuse2:
    name: FreeBSD (with FUSE v2)
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Build on VM
        uses: vmactions/freebsd-vm@83b151f58c6047089f4c80eb5ba2039d158ce093 # v1.5.3
        with:
          copyback: true
          sync: sshfs
          prepare: |
            pkg remove -y fusefs-libs3
            pkg install -y \
              avahi \
              fusefs-libs \
              libedit \
              libgcrypt \
              libiconv \
              meson \
              pkgconf
          run: |
            set -e
            meson setup build \
              -Dpkg_config_path=/usr/local/libdata/pkgconfig
            meson compile -C build
            meson test -C build
            meson install -C build
            afpcmd -h
      - name: Upload meson logs
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: meson-logs-${{ github.job }}
          path: build/meson-logs

  build-freebsd-fuse3:
    name: FreeBSD (with FUSE v3)
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Build on VM
        uses: vmactions/freebsd-vm@83b151f58c6047089f4c80eb5ba2039d158ce093 # v1.5.3
        with:
          copyback: true
          sync: sshfs
          prepare: |
            pkg install -y \
              avahi \
              fusefs-libs3 \
              libedit \
              libgcrypt \
              libiconv \
              meson \
              pkgconf
          run: |
            set -e
            meson setup build \
              -Dpkg_config_path=/usr/local/libdata/pkgconfig
            meson compile -C build
            meson test -C build
            meson install -C build
            afpcmd -h
      - name: Upload meson logs
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: meson-logs-${{ github.job }}
          path: build/meson-logs

  build-netbsd:
    name: NetBSD (with FUSE v2)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Build on VM
        uses: vmactions/netbsd-vm@e7ac71b97abbe8437cec8859a5acf72dfa6a8be0 # v1.4.5
        with:
          copyback: true
          prepare: |
            export PKG_PATH="http://ftp.NetBSD.org/pub/pkgsrc/packages/NetBSD/$(uname -p)/$(uname -r|cut -f '1 2' -d.)/All"
            pkg_add \
              fuse \
              gcc13 \
              libgcrypt \
              meson \
              pkg-config
          run: |
            set -e
            meson setup build
            meson compile -C build
            meson test -C build
            meson install -C build
      - name: Upload meson logs
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: meson-logs-${{ github.job }}
          path: build/meson-logs

  build-openbsd:
    name: OpenBSD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Build on VM
        uses: vmactions/openbsd-vm@e6c68b637a12e83519688d115d57d5b0b53923cd # v1.4.6
        with:
          copyback: true
          sync: sshfs
          prepare: |
            pkg_add -I \
              avahi \
              libgcrypt \
              meson
          run: |
            set -e
            meson setup build
            meson compile -C build
            meson test -C build
            meson install -C build
            afpcmd -h
      - name: Upload meson logs
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: meson-logs-${{ github.job }}
          path: build/meson-logs

  build-omnios:
    name: OmniOS
    runs-on: ubuntu-latest
    timeout-minutes: 24
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Build on VM
        uses: vmactions/omnios-vm@027e3ec08fed6fb740ab5f300c2605f9de02997a # v1.3.4
        with:
          release: "r151056-build"
          copyback: true
          prepare: |
            set -e
            pkg install \
              build-essential \
              pkg-config
            curl --proto '=https' --location --fail -o bootstrap.tar.gz "${{ env.SMARTOS_BOOTSTRAP_URL }}"
            bootstrap_sha256=$(/bin/digest -a sha256 bootstrap.tar.gz)
            if [ "$bootstrap_sha256" != "${{ env.SMARTOS_BOOTSTRAP_SHA256 }}" ]; then
              echo "bootstrap.tar.gz SHA-256 mismatch" >&2
              exit 1
            fi
            tar -zxpf bootstrap.tar.gz -C /
            export PATH=/opt/local/sbin:/opt/local/bin:/usr/gnu/bin:/usr/bin:/usr/sbin:/sbin:$PATH
            pkgin -y install \
              avahi \
              meson \
              libgcrypt
          run: |
            set -e
            export PATH=/opt/local/sbin:/opt/local/bin:/usr/gnu/bin:/usr/bin:/usr/sbin:/sbin:$PATH
            export LD_LIBRARY_PATH=/opt/local/lib
            export PKG_CONFIG_PATH=/opt/local/lib/pkgconfig
            meson setup build \
              --prefix=/opt/local \
              -Denable-fuse=false \
              -Dpkg_config_path=/opt/local/lib/pkgconfig
            meson compile -C build
            meson test -C build
            meson install -C build
            afpcmd -h
      - name: Upload meson logs
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: meson-logs-${{ github.job }}
          path: build/meson-logs

  build-openindiana:
    name: OpenIndiana
    runs-on: ubuntu-latest
    timeout-minutes: 24
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Build on VM
        uses: vmactions/openindiana-vm@52f16d4534fe3edd9d9621621c238398d4d2a698 # v1.1.5
        with:
          release: "202510-build"
          copyback: true
          prepare: |
            set -e
            pkg install \
              developer/build/meson \
              developer/build/ninja \
              developer/build/pkg-config \
              developer/gcc-14 \
              library/libedit \
              system/library/security/libgcrypt
          run: |
            set -e
            export PKG_CONFIG_PATH=/usr/lib/amd64/pkgconfig
            meson setup build \
              -Denable-fuse=false \
              -Dpkg_config_path=/usr/lib/amd64/pkgconfig
            meson compile -C build
            meson test -C build
            meson install -C build
            /usr/local/bin/afpcmd -h
      - name: Upload meson logs
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: meson-logs-${{ github.job }}
          path: build/meson-logs

  build-solaris:
    name: Solaris 11
    runs-on: ubuntu-latest
    timeout-minutes: 24
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Build on VM
        uses: vmactions/solaris-vm@315163f088b66e55bbcc45928bd224d4973b2312 # v1.3.8
        with:
          copyback: true
          sync-time: true
          sync: nfs
          prepare: |
            set -e
            pkg install \
              gcc \
              library/libedit \
              libgcrypt \
              meson \
              ninja \
              pkg-config
          run: |
            set -e
            export PKG_CONFIG_PATH=/usr/lib/amd64/pkgconfig
            meson setup build \
              --prefix=/usr/local \
              -Denable-fuse=false \
              -Dpkg_config_path=/usr/lib/amd64/pkgconfig
            meson compile -C build
            meson test -C build
            meson install -C build
            /usr/local/bin/afpcmd -h
      - name: Upload meson logs
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: meson-logs-${{ github.job }}
          path: build/meson-logs
